language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on  

# before_script:
#   - go install -mod vendor github.com/golangci/golangci-lint/cmd/golangci-lint

os:
- linux  

# Skip the install step. Don't `go get` dependencies. Only build with the code in vendor/
install: true

script:
  # - golangci-lint run
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com

