language: go

go:
  - "1.10"
  - "1.11"

os:
- linux

before_install:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.10.2
script:
- go build .
- golangci-lint run
- go test -v .

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com