language: go

go:
  - "1.10"
  - "1.11"

os:
- linux  

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.10.2

script:
  - golangci-lint run
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - alastairruhm@gmail.com

